# 1년은 몇초인지 출력

input_year = int(input("햇수 입력: "))

DAYS_PER_YEAR = 365
HOURS_PER_DAY = 24
MINUTES_PER_HOUR = 60
SECONDS_PER_MINUTES = 60

year_to_second = input_year*DAYS_PER_YEAR * \
    HOURS_PER_DAY*MINUTES_PER_HOUR*SECONDS_PER_MINUTES

print(f"{input_year}년은 {year_to_second}초입니다.")

# 45분간 업무 10분 휴식 전체 근무시간 480분
# 휴식 시간의 합계는 얼마

WORKING_MINUTES = 45
REST_MINUTES = 10
WHOLE_WORKING_MINUTES = 480
ONE_SET_MINUTES = WORKING_MINUTES+REST_MINUTES
REST_TIMES = WHOLE_WORKING_MINUTES//ONE_SET_MINUTES
WHOLE_REST_TIMES = REST_TIMES*REST_MINUTES

print(WHOLE_REST_TIMES)
